version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80" # Expose the frontend on port 5173
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose the backend on port 5000
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Add other necessary environment variables like connection strings

networks:
  app-network:
    driver: bridge
